### ISSUE TITLE
Won't start inside Jupyter Lab

### ISSUE THREAD

**Issue by jpcaram** [aosingh/sqlite_rx#2]
This is what I get when starting the server within Jupyter Lab:

```
server = SQLiteServer(database=":memory:",
    bind_address="tcp://127.0.0.1:5003")
server.start()

Process SQLiteServer-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/xxxxxxx/lib/python3.6/site-packages/sqlite_rx/server.py", line 179, in run
    self.loop.start()
  File "/home/xxxxxxx/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 429, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

It appears that the process that SQLiteServer creates is not properly isolated from the calling process. Jupyter already starts an asyncio loop in the ipython kernel and SQLiteServer is seeing it, referencing it and not starting a new one.

**Comment by aosingh** [comment]
#3 

Hi @jpcaram 

Thank you for reporting this issue. I have released a fix in sqlite_rx version 0.9.98.  This release also includes support for PyPy

I tested starting the server in a Jupyter  Lab notebook and was able to send queries to the server. 

Please let me know if you face this issue in the latest version of sqlite_rx. 

<img width="1136" alt="Screen Shot 2020-04-26 at 11 24 55 PM" src="https://user-images.githubusercontent.com/14945417/80341435-4e72e780-8817-11ea-9a86-edf76ab3898b.png">

**Comment by jpcaram** [comment]
Hi @aosingh , your fix worked perfectly. Thanks for the quick response!

**Comment by aosingh** [comment]
Sure. Closing this issue.
